Create homework_5.md
lode00/epam_homework pull request #5
Opened 2021-12-15 05:57 UTC by lode00

2021-12-15 05:59 UTC, lode00 commented
@morggoth shall you check it ?

Lobach Denis

2021-12-16 12:14 UTC, morggoth requested changes

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +```
В этих строках явно путаница какая-то. Там где нужно завершить процесс, ты отправляешь SIGCONT, там где нужно продолжить работу, ты говоришь им SIGTERM.

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +```
Тут ты пристрелил процесс по PID, а не по job ID.

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +[lode00@localhost ~]$ sleep 3000 1> out.log 2>err.log &
Все ок, но единицу можно пропускать, то есть достаточно написать `... > out.log ...`

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +stdin.
И откуда же sleep принимает stdin?

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +* List all ESTABLISHED TCP connections ONLY with lsof
тут все ок

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +2       0        homework               echo 'echo Hello > /opt/hello'> /home/script.sh | bash ~/script.sh
Не самое рациональное решение, потому что скрипт будет каждые 2 дня перезаписываться. Кроме того, `/home/script.sh` не то же самое, что `~/script.sh`

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +@reboot sleep 60 && echo 'echo Hello > /opt/hello'> /home/script.sh | bash ~/script.sh
Аналогичный комментарий по поводу перезаписывания скрипта и того, что именно такая комбинация не будет исполняться + было бы не плохо тут использовать другой файл.

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +```
Учитывая предыдущие комментарии, этот результат получен не по условиям задания.

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +2       0        homework               echo 'echo Hello > /opt/hello'> /home/script.sh | bash ~/script.sh
Еще один момент, зачем именно тут нужен пайп? Не лучше ли вместо него использовать другую конструкцию?

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +Decription=First daemon
Очепятка, на что явно указывает вывод `systemctl status`:

```bash
[root@localhost ~]# systemctl status  one.service
● one.service
   Loaded: loaded (/etc/systemd/system/one.service; static; vendor preset: disabled)
   Active: inactive (dead)

Dec 16 12:08:21 localhost.localdomain systemd[1]: [/etc/systemd/system/one.service:2] Unknown lvalue 'Decription' in section 'Unit'
Dec 16 12:08:43 localhost.localdomain systemd[1]: [/etc/systemd/system/one.service:2] Unknown lvalue 'Decription' in section 'Unit'
Dec 16 12:09:05 localhost.localdomain systemd[1]: [/etc/systemd/system/one.service:2] Unknown lvalue 'Decription' in section 'Unit'
```

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +Decription=Second daemon
аналогично

2021-12-16 12:14 UTC, morggoth commented on homework_5.md
> +var3=/etc/systemd/system/second.timer
Не ошибка (по крайней мере не здесь), но лучше сразу привыкать давать переменным осмысленные имена.

2021-12-16 13:24 UTC, lode00 commented
@morggoth  вроде исправил, посмотрите, пожалуйста.

2021-12-20 13:17 UTC, morggoth reviewed
Молодец, можно мержить.

2021-12-20 15:15 UTC, merged